/* Sensory Garden Print: matte paper texture, ink-like color fields, plant-inspired emotive shapes, and bounded artwork that never collides with content. */
import { useMemo, useState } from "react";
import { ArrowRight, Check, ChevronRight, Headphones, Menu, Send, Volume2, VolumeX, X } from "lucide-react";

type BrailleCell = number[];
declare global { interface Window { KB?: { brailleCells: (text: string) => BrailleCell[]; toUnicodeBraille: (text: string) => string }; } }

const FALLBACK_CELLS: Record<string, BrailleCell[]> = { "바": [[1, 2, 4, 5]], "다": [[1, 4, 5]], "마": [[1, 3, 4]], "센서리": [[2, 3, 4], [1, 2, 3, 5], [2, 3, 4], [1, 2, 3, 5], [2, 4]] };
const DOT_ORDER = [1, 4, 2, 5, 3, 6];
const lesson = { answer: "바", options: ["바", "다", "마"], prompt: "닷패드 위 점자를 만져 보고, 알맞은 글자를 골라 보세요.", hint: "왼쪽 윗점과 오른쪽 가운데·아랫점의 위치를 천천히 확인해 보세요." };

function getCells(text: string): BrailleCell[] { if (typeof window !== "undefined" && window.KB) return window.KB.brailleCells(text); return FALLBACK_CELLS[text] ?? text.slice(0, 8).split("").map((_, index) => [1, 2 + (index % 3)]); }
function toBraille(text: string) { if (typeof window !== "undefined" && window.KB) return window.KB.toUnicodeBraille(text); return getCells(text).map((dots) => String.fromCodePoint(0x2800 + dots.reduce((value, dot) => value | (1 << (dot - 1)), 0))).join(""); }
function DotGrid({ dots, compact = false }: { dots: BrailleCell; compact?: boolean }) { return <span className={compact ? "cell-small" : "cell-large"} aria-hidden="true">{DOT_ORDER.map((dot) => <i key={dot} className={dots.includes(dot) ? "up" : ""} />)}</span>; }
function BrandMark() { return <span className="brand-mark" aria-hidden="true">{Array.from({ length: 6 }, (_, index) => <i key={index} />)}</span>; }
function ShapeFace({ color = "coral", kind = "round", className = "" }: { color?: string; kind?: string; className?: string }) { return <span className={`shape-face ${color} ${kind} ${className}`} aria-hidden="true"><span className="face-eyes"><i /><i /></span><span className="face-mouth" /></span>; }
function PlantFriend({ color = "sky", className = "" }: { color?: string; className?: string }) { return <span className={`plant-friend ${className}`} aria-hidden="true"><i className={`plant-leaf leaf-left ${color}`} /><i className={`plant-leaf leaf-right ${color}`} /><i className={`plant-stem ${color}`} /><ShapeFace color={color} kind="bud" /></span>; }

export default function Home() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [voiceOn, setVoiceOn] = useState(true);
  const [selected, setSelected] = useState<string | null>(null);
  const [checked, setChecked] = useState(false);
  const [completed, setCompleted] = useState(false);
  const [studioText, setStudioText] = useState("센서리");
  const [liveMessage, setLiveMessage] = useState("오늘의 촉각 학습지가 도착했어요.");
  const lessonDots = useMemo(() => getCells(lesson.answer)[0] ?? [], []);
  const studioCells = useMemo(() => getCells(studioText || "점자").slice(0, 14), [studioText]);
  const goTo = (id: string) => { setMobileOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const speak = (message: string) => { setLiveMessage(message); if (voiceOn && "speechSynthesis" in window) { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(message); utterance.lang = "ko-KR"; utterance.rate = 1.02; window.speechSynthesis.speak(utterance); } };
  const choose = (option: string) => { if (!completed) { setSelected(option); setChecked(false); speak(`${option}을 골랐어요. 정답을 확인해 보세요.`); } };
  const check = () => { if (!selected) return speak("먼저 글자 하나를 골라 보세요."); setChecked(true); if (selected === lesson.answer) { setCompleted(true); speak("맞았어요! 바가 닷패드 위에 또렷하게 올라왔어요. 오늘의 첫 문제를 완료했어요."); } else speak("아직 아니에요. 힌트를 듣고 손끝의 점을 다시 확인해 보세요."); };

  return <div className="garden-site" id="top">
    <a className="sr-only" href="#today">오늘의 학습지로 바로가기</a><div className="sr-only" aria-live="polite">{liveMessage}</div>
    <header className="garden-header"><div className="page-width garden-nav-row"><a href="#top" className="garden-brand" aria-label="Sensory 홈"><BrandMark /><span>sensory</span><small>TOUCH &amp; GROW</small></a><nav className="garden-nav" aria-label="주 메뉴"><a href="#today">오늘의 한 장</a><a href="#how">왜 Sensory?</a><a href="#curriculum">학습 정원</a><a href="#studio">점자 실험실</a></nav><button className="header-action" onClick={() => goTo("today")}>시작하기 <ArrowRight size={15} /></button><button className="mobile-menu" onClick={() => setMobileOpen(!mobileOpen)} aria-label="메뉴 열기" aria-expanded={mobileOpen}>{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button></div><nav className="mobile-nav" aria-label="모바일 메뉴" hidden={!mobileOpen}><a href="#today" onClick={() => setMobileOpen(false)}>오늘의 한 장</a><a href="#how" onClick={() => setMobileOpen(false)}>왜 Sensory?</a><a href="#curriculum" onClick={() => setMobileOpen(false)}>학습 정원</a><a href="#studio" onClick={() => setMobileOpen(false)}>점자 실험실</a></nav></header>

    <main>
      <section className="garden-hero" aria-labelledby="hero-title"><div className="page-width hero-grid"><div className="hero-copy"><span className="capsule-label"><i /><i /><i /> TODAY'S SHEET <b>01</b></span><h1 id="hero-title">손끝에서<br /><em>피어나는</em><br />오늘의 공부.</h1><p>오늘의 학습지가 닷패드에 도착해요. 만지고, 듣고, 답을 찾으며 내 감각으로 한 걸음씩 자라요.</p><div className="hero-actions"><button className="ink-button" onClick={() => goTo("today")}>오늘의 학습지 열기 <ArrowRight size={17} /></button><button className="paper-button" onClick={() => goTo("how")}>어떻게 배우나요?</button></div><span className="micro-copy">TOUCH · LISTEN · LEARN · SMILE</span></div><div className="hero-garden" aria-label="식물형 감정 캐릭터와 닷패드를 표현한 Sensory 일러스트"><div className="garden-sun" /><PlantFriend color="sky" className="hero-plant one" /><PlantFriend color="pink" className="hero-plant two" /><ShapeFace color="coral" kind="leaf" className="hero-face" /><div className="hero-pad"><span className="pad-label">DOTPAD · READY</span><span className="pad-line"><i /><i /><i /><i /><i /><i /><i /><i /></span><span className="pad-line short"><i /><i /><i /><i /></span></div></div></div></section>

      <section className="black-ribbon" aria-label="Sensory의 학습 가치"><div className="page-width ribbon-grid"><ShapeFace color="pink" kind="round" className="ribbon-face" /><p>공부가 <strong>자라는</strong><br />감각이 될 수 있을까?</p><span className="ribbon-route"><i />●<i />●<i />●</span><p className="ribbon-small">매일 한 장이<br />나를 키우니까!</p></div></section>

      <section id="today" className="daily-section" aria-labelledby="today-title"><div className="page-width"><div className="section-copy"><span className="capsule-label"><i /><i /><i /> DAILY TACTILE PAPER <b>01</b></span><h2 id="today-title">오늘의 한 장이<br />손끝에 도착했어요.</h2><p>하나의 문제부터 가볍게 시작해요. 닷패드에 올라온 점을 느끼고, 맞는 글자를 골라 보세요.</p></div><div className="daily-layout"><aside className="daily-intro"><span>TUE 08 · 26</span><ShapeFace color="coral" kind="leaf" className="daily-face" /><h3>두근두근<br />첫 글자 찾기</h3><p>오늘의 감각 미션이에요!</p><ol><li className="done"><b>1</b> 학습지가 도착했어요</li><li><b>2</b> 손끝으로 점을 확인해요</li><li><b>3</b> 오늘의 “아하!”를 모아요</li></ol><PlantFriend color="lime" className="side-plant" /></aside><div className="daily-task"><div className="task-bar"><span><b>01</b> BRAILLE POP QUIZ</span><button onClick={() => { const next = !voiceOn; setVoiceOn(next); setLiveMessage(next ? "음성 안내를 켰어요." : "음성 안내를 껐어요."); }} aria-pressed={voiceOn}>{voiceOn ? <Volume2 size={15} /> : <VolumeX size={15} />}{voiceOn ? "소리 켜짐" : "소리 꺼짐"}</button></div><div className="question-block"><span>FEEL THE DOTS</span><h3>{lesson.prompt}</h3><p>이 미리보기의 점은 실제 닷패드에서 손끝으로 느끼는 핀의 위치를 나타냅니다.</p></div><div className="dotpad-preview"><span><small>DOTPAD · 6 DOT CELL</small><b>지금 손끝에 올라온 점</b></span><DotGrid dots={lessonDots} /></div><div className="answer-options" role="group" aria-label="글자 선택지">{lesson.options.map((option, index) => { const picked = option === selected; const state = checked ? option === lesson.answer ? "correct" : picked ? "wrong" : "" : picked ? "picked" : ""; return <button className={`answer-option ${state}`} key={option} onClick={() => choose(option)} disabled={completed} aria-pressed={picked}><ShapeFace color={index === 0 ? "yellow" : index === 1 ? "pink" : "sky"} kind="mini" /><b>{option}</b><small>{toBraille(option)}</small></button>; })}</div>{completed ? <div className="success-note"><span>✦</span><div><b>짜잔! 오늘의 첫 문제를 풀었어요.</b><p>바가 닷패드 위에서 또렷하게 올라왔어요.</p></div></div> : <div className="answer-footer"><p className={checked ? selected === lesson.answer ? "yes" : "no" : ""}>{checked ? selected === lesson.answer ? "맞았어요. 도트를 다시 느껴 보세요!" : "아직 아니에요. 손끝의 점을 다시 따라가 볼까요?" : "글자를 고른 뒤 정답을 확인해 보세요."}</p>{checked && selected !== lesson.answer ? <button onClick={() => speak(lesson.hint)}><Headphones size={15} />힌트 듣기</button> : <button onClick={check}>정답 확인 <ChevronRight size={15} /></button>}</div>}</div></div></div></section>

      <section id="how" className="how-section" aria-labelledby="how-title"><div className="page-width how-grid"><div className="how-copy"><span className="capsule-label"><i /><i /><i /> WHY SENSORY? <b>?</b></span><h2 id="how-title">눈으로만<br />배우지 않아도<br /><em>괜찮아.</em></h2><p>Sensory는 촉각, 음성, 화면 정보를 함께 연결해요. 그래서 다음에 뭘 해야 할지, 내가 맞혔는지 스스로 알 수 있어요.</p><button className="paper-dark-button" onClick={() => goTo("studio")}>내 글자도 점자로 <ArrowRight size={16} /></button></div><div className="growth-poster" aria-label="감정 도형 캐릭터와 촉각 학습의 흐름을 표현한 포스터"><div className="poster-dots"><i /><i /><i /><i /><i /><i /></div><PlantFriend color="sky" className="poster-plant top" /><PlantFriend color="pink" className="poster-plant bottom" /><ShapeFace color="lime" kind="leaf" className="poster-face" /><p>TOUCH,<br />THEN GROW!</p></div></div></section>

      <section id="curriculum" className="curriculum-section" aria-labelledby="curriculum-title"><div className="page-width"><div className="curriculum-header"><div><span className="capsule-label"><i /><i /><i /> TACTILE GARDEN <b>04</b></span><h2 id="curriculum-title">손끝으로 만나는<br />작은 학습 정원.</h2></div><p>매일의 작은 과제가 이어져 읽기부터 수, 언어, 촉각 그림까지 나만의 감각 언어가 됩니다.</p></div><div className="curriculum-grid"><article className="curriculum-card purple"><ShapeFace color="purple" kind="leaf" /><span>01 · LITERACY</span><h3>점자 문해</h3><p>자모부터 문장까지 읽기의 리듬을 익혀요.</p><b>⠨⠎⠢⠨</b></article><article className="curriculum-card yellow"><PlantFriend color="yellow" /><span>02 · MATH</span><h3>수학</h3><p>수와 도형의 관계를 손끝으로 만나요.</p><b>⠠⠍⠚⠁</b></article><article className="curriculum-card pink"><ShapeFace color="pink" kind="round" /><span>03 · ENGLISH</span><h3>영어</h3><p>소리와 철자를 함께 점자로 익혀요.</p><b>⠻⠎</b></article><article className="curriculum-card lime"><PlantFriend color="lime" /><span>04 · GRAPHICS</span><h3>촉각 그림</h3><p>지도와 구조도를 감각 정보로 바꿔요.</p><b>⠰⠭⠫⠁</b></article></div></div></section>

      <section id="studio" className="studio-section" aria-labelledby="studio-title"><div className="page-width studio-grid"><div className="studio-copy"><span className="capsule-label"><i /><i /><i /> BRAILLE LAB <b>+ +</b></span><h2 id="studio-title">내가 쓴 말이<br /><em>점점점</em> 하고<br />올라와요.</h2><p>내 이름이나 좋아하는 단어를 적어 보세요. Sensory가 바로 점자로 바꿔 닷패드 한 줄에 보여 줍니다.</p><ShapeFace color="sky" kind="round" className="studio-face" /></div><div className="studio-console"><div className="console-title"><span><Send size={15} /> LIVE DOTPAD PREVIEW</span><b>READY!</b></div><label className="sr-only" htmlFor="studio-input">점자로 바꿀 한글, 영어, 숫자를 입력</label><div className="console-input"><input id="studio-input" value={studioText} maxLength={20} onChange={(event) => { setStudioText(event.target.value); setLiveMessage("닷패드 미리보기를 갱신했어요."); }} placeholder="예: 내 이름" /><button onClick={() => speak(studioText || "입력한 글자가 없습니다.")} aria-label="입력한 글자 듣기"><Volume2 size={18} /></button></div><p className="studio-braille" aria-live="polite">{toBraille(studioText || "점자")}</p><div className="studio-dotpad" aria-label={`${studioText || "점자"} 점자 출력 미리보기`}>{studioCells.map((cell, index) => <DotGrid compact dots={cell} key={`${index}-${cell.join("-")}`} />)}</div><div className="console-footer"><span>DOTPAD · {studioCells.length} / 20 CELLS</span><button onClick={() => { setStudioText("센서리"); speak("센서리 예시로 되돌렸어요."); }}>예시로 돌아가기 <ChevronRight size={14} /></button></div></div></div></section>
    </main>
    <footer className="garden-footer"><div className="page-width footer-row"><div><span className="capsule-label"><i /><i /><i /> SEE YOU TOMORROW <b>✦</b></span><h2>내일도<br />손끝에서 만나.</h2></div><PlantFriend color="pink" className="footer-plant" /><button className="footer-button" onClick={() => goTo("today")}>오늘의 한 장 다시 보기 <ArrowRight size={16} /></button></div><div className="page-width footer-bottom"><span className="garden-brand"><BrandMark /><b>sensory</b></span><span>닷패드 연동 촉각 학습 경험 컨셉 데모</span></div></footer>
  </div>;
}
