/* Sensory Garden Print report: a clear parent-facing weekly overview built from the same 7-day sample learning record. */
import { ArrowLeft, ArrowRight, BookOpenCheck, ChartNoAxesCombined, Check, Clock3, Ear, House, Leaf, PanelsTopLeft, Sparkles, Volume2 } from "lucide-react";
import { characters, dailyLessons, loadProgress, type CharacterKey, type DailyLesson } from "@/lib/dailyContent";
import { publicAsset } from "@/lib/publicAsset";

function ShapeBadge({ accent }: { accent: string }) { const colorMap: Record<string, CharacterKey> = { coral: "momo", sky: "pio", pink: "lulu", lime: "nabi", purple: "nabi" }; const identity = colorMap[accent] ?? "momo"; return <span className={`report-shape character-breathe ${accent}`} data-character={identity} aria-hidden="true"><span className="face-eyes"><span className="googly-eye"><i className="googly-pupil" data-googly-pupil /><i className="blink-lid" /></span><span className="googly-eye"><i className="googly-pupil" data-googly-pupil /><i className="blink-lid" /></span></span><b /></span>; }
function ProgressBar({ completed, total }: { completed: number; total: number }) { return <div className="progress-track" aria-label={`${total}개 중 ${completed}개 완료`}><span style={{ width: `${(completed / total) * 100}%` }} /></div>; }

export default function Report() {
  const isGitHubPagesBuild = import.meta.env.VITE_GITHUB_PAGES === "true";
  const base = import.meta.env.BASE_URL;
  const homeHref = isGitHubPagesBuild ? base : "/";
  const todayHref = isGitHubPagesBuild ? `${base}#today` : "/#today";
  const studioHref = isGitHubPagesBuild ? `${base}#studio` : "/#studio";
  const reportHref = isGitHubPagesBuild ? `${base}?view=report` : "/report";
  const completedIds = typeof window === "undefined" ? [] : loadProgress();
  const completedLessons = dailyLessons.filter((lesson) => completedIds.includes(lesson.id));
  const completedCount = completedLessons.length;
  const minutes = completedCount * 10;
  const current = dailyLessons.find((lesson) => !completedIds.includes(lesson.id)) ?? dailyLessons[dailyLessons.length - 1];
  const subjects: DailyLesson["subject"][] = ["점자 문해", "수학", "영어", "촉각 그림"];
  const recent = completedLessons.slice(-3).reverse();

  return <div className="report-page" style={{ "--toy-island": `url(${publicAsset("/manus-storage/sensory-3d-toy-island_077dd413.png", "sensory-3d-toy-island.webp")})`, "--neon-stage": `url(${publicAsset("/manus-storage/sensory-neon-character-stage_744636b3.png", "sensory-neon-character-stage.webp")})` } as React.CSSProperties}>
    <header className="report-header"><div className="report-width report-nav"><a href={homeHref} className="report-brand"><span className="report-mark">⠿</span><b>sensory</b><small>PARENT REPORT</small></a><a className="report-back" href={homeHref}><ArrowLeft size={15} />학습지로 돌아가기</a></div></header>
    <main className="report-width report-main">
      <section className="report-intro"><div><span className="report-label">WEEKLY LEARNING REPORT · DEMO</span><h1>이번 주,<br /><em>손끝의 성장</em>을 보세요.</h1><p>이 화면은 현재 브라우저에서 진행한 7일 샘플 학습 기록을 요약합니다. 실제 서비스에서는 보호자와 코치가 아이의 학습 흐름을 함께 확인할 수 있습니다.</p></div><div className="report-plant"><ShapeBadge accent="sky" /><span className="report-leaves"><i /><i /><i /></span><b>이번 주의<br />감각 정원</b></div></section>
      <section className="report-summary-grid" aria-label="이번 주 핵심 요약"><article className="summary-card orange"><span>이번 주 완료</span><strong>{completedCount}<small>/ 7</small></strong><p>오늘의 한 장을 끝까지 풀었어요.</p><ShapeBadge accent="coral" /></article><article className="summary-card green"><span>집중한 시간</span><strong>{minutes}<small>분</small></strong><p>하루 10분의 작은 리듬이에요.</p><span className="summary-icon"><Clock3 size={21} /></span></article><article className="summary-card purple"><span>가장 자주 만난 영역</span><strong>{completedLessons[0]?.subject ?? "점자 문해"}</strong><p>다음 학습은 다른 감각 영역으로 이어져요.</p><span className="summary-icon"><Leaf size={21} /></span></article></section>
      <section className="report-board"><div className="report-section-head"><div><span className="report-label">WEEKLY RHYTHM</span><h2>7일 학습지의 흐름</h2></div><span className="report-note">완료한 날은 캐릭터의 꽃잎이 피어요.</span></div><div className="week-strip">{dailyLessons.map((lesson) => { const done = completedIds.includes(lesson.id); const character = characters[lesson.character]; return <article className={`week-day ${done ? "done" : ""} ${lesson.id === current.id ? "current" : ""}`} key={lesson.id}><span>{lesson.weekday}</span><ShapeBadge accent={character.accent} /><b>{done ? <Check size={16} /> : lesson.id === current.id ? "NOW" : "···"}</b><small>{lesson.title}</small></article>; })}</div><div className="week-progress"><div><span>이번 주 진행률</span><ProgressBar completed={completedCount} total={7} /></div><b>{Math.round((completedCount / 7) * 100)}%</b></div></section>
      <section className="report-detail-grid"><article className="report-card area-card"><span className="report-label">LEARNING AREAS</span><h2>영역별 학습 현황</h2><div className="area-list">{subjects.map((subject, index) => { const total = dailyLessons.filter((lesson) => lesson.subject === subject).length; const done = completedLessons.filter((lesson) => lesson.subject === subject).length; const accents = ["coral", "sky", "purple", "lime"]; return <div key={subject}><span className={`area-dot ${accents[index]}`} /><p><b>{subject}</b><small>{done} / {total} 완료</small></p><ProgressBar completed={done} total={total} /></div>; })}</div></article><article className="report-card coach-card"><span className="report-label">NEXT SUGGESTION</span><h2>다음 학습지는<br /><em>{current.title}</em>이에요.</h2><p>{current.description}</p><div className="coach-row"><ShapeBadge accent={characters[current.character].accent} /><span><b>{characters[current.character].name}의 안내</b><small>“{characters[current.character].greeting}”</small></span></div><a href={todayHref}>오늘의 학습지로 이동 <ArrowRight size={15} /></a></article></section>
      <section className="report-board recent-board"><div className="report-section-head"><div><span className="report-label">RECENT MOMENTS</span><h2>최근의 작은 성취</h2></div><span className="report-note"><Volume2 size={15} />캐릭터 피드백과 함께 기록돼요.</span></div>{recent.length ? <div className="recent-list">{recent.map((lesson) => <article key={lesson.id}><ShapeBadge accent={characters[lesson.character].accent} /><div><b>{lesson.weekday}요일 · {lesson.title}</b><p>{characters[lesson.character].name}: “{characters[lesson.character].correct}”</p></div><span className="recent-complete"><Check size={16} />완료</span></article>)}</div> : <div className="report-empty"><Ear size={22} /><p>첫 학습지를 마치면, 여기에 캐릭터의 응원 기록이 쌓여요.</p></div>}</section>
      <p className="report-footnote"><Sparkles size={14} />이 대시보드는 샘플 학습 데이터로 구성된 데모입니다. 실제 보호자 기능은 사용자 계정과 학습 기록 저장 기능을 연동해 확장할 수 있습니다.</p>
    </main>
    <nav className="mobile-dock" aria-label="모바일 빠른 탐색"><a href={homeHref}><House size={18} /><span>홈</span></a><a href={todayHref}><BookOpenCheck size={18} /><span>학습</span></a><a href={studioHref}><PanelsTopLeft size={18} /><span>점자</span></a><a className="current" href={reportHref}><ChartNoAxesCombined size={18} /><span>리포트</span></a></nav>
  </div>;
}
